#!/usr/bin/env tsx
import { callMcpTool } from "@merl-ai/mcp-toolbox-runtime";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";

// Generated by mcp-toolbox. Do not edit by hand.

export interface MigratepagestoworkersguideInput {}

export type MigratepagestoworkersguideOutput = unknown;


/**
 * ALWAYS read this guide before migrating Pages projects to Workers.
 *
 * MCP server: `cloudflare-observability`
 * MCP tool: `migrate_pages_to_workers_guide`
 * @param input Tool input
 * @returns Tool output
 */
export async function migratePagesToWorkersGuide(input: MigratepagestoworkersguideInput): Promise<MigratepagestoworkersguideOutput> {
  return await callMcpTool<MigratepagestoworkersguideOutput>({
    serverName: "cloudflare-observability",
    toolName: "migrate_pages_to_workers_guide",
    input,
  });
}

// CLI execution block
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  (async () => {
    try {
      let inputStr = "";
      if (process.stdin.isTTY) {
        // No stdin available, use empty object
        inputStr = "{}";
      } else {
        // Read from stdin (file descriptor 0)
        try {
          inputStr = readFileSync(0, "utf-8").trim();
        } catch {
          // Fallback if readFileSync fails
          inputStr = "";
        }
        if (!inputStr) {
          inputStr = "{}";
        }
      }
      
      const input = JSON.parse(inputStr) as MigratepagestoworkersguideInput;
      const result = await migratePagesToWorkersGuide(input);
      console.log(JSON.stringify(result, null, 2));
      process.exit(0);
    } catch (error) {
      console.error("Error:", error instanceof Error ? error.message : String(error));
      if (error instanceof Error && error.stack) {
        console.error(error.stack);
      }
      process.exit(1);
    }
  })();
}
