#!/usr/bin/env tsx
import { callMcpTool } from "mcp-toolbox-runtime";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";

// Generated by mcp-toolbox. Do not edit by hand.

export interface ObservabilitykeysInput {
  keysQuery: Record<string, unknown>;
}

export type ObservabilitykeysOutput = unknown;

/**
 * Find keys in the Workers Observability Data

## Best Practices
- Set a high limit (1000+) to ensure you see all available keys
- Add the $metadata.service filter to narrow results to a specific Worker

## Troubleshooting
- If expected fields are missing, verify the Worker is actively logging
- For empty results, try broadening your time range

 *
 * MCP server: `cloudflare-observability`
 * MCP tool: `observability_keys`
 * @param input Tool input
 * @returns Tool output
 */
export async function observabilityKeys(
  input: ObservabilitykeysInput,
): Promise<ObservabilitykeysOutput> {
  return await callMcpTool<ObservabilitykeysOutput>({
    serverName: "cloudflare-observability",
    toolName: "observability_keys",
    input,
  });
}

// CLI execution block
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  (async () => {
    try {
      let inputStr = "";
      if (process.stdin.isTTY) {
        // No stdin available, use empty object
        inputStr = "{}";
      } else {
        // Read from stdin (file descriptor 0)
        try {
          inputStr = readFileSync(0, "utf-8").trim();
        } catch {
          // Fallback if readFileSync fails
          inputStr = "";
        }
        if (!inputStr) {
          inputStr = "{}";
        }
      }

      const input = JSON.parse(inputStr) as ObservabilitykeysInput;
      const result = await observabilityKeys(input);
      console.log(JSON.stringify(result, null, 2));
      process.exit(0);
    } catch (error) {
      console.error("Error:", error instanceof Error ? error.message : String(error));
      if (error instanceof Error && error.stack) {
        console.error(error.stack);
      }
      process.exit(1);
    }
  })();
}
