#!/usr/bin/env tsx
import { callMcpTool } from "@merl-ai/mcp-toolbox-runtime";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";

// Generated by mcp-toolbox. Do not edit by hand.

export interface ObservabilitykeysInput {
  keysQuery: {
    /**
     * Timeframe for your query, which can be either absolute or relative.
     *
     *   • Absolute timeframe: Specify exact start and end times in ISO-8601 format (e.g., "2025-04-29T14:30:00Z").
     *   • Relative timeframe: Specify a reference time and an offset (e.g., reference="2025-04-29T14:30:00Z", offset="-30m").
     *
     *   Examples:
     *   - Absolute: from="2025-04-01T00:00:00Z", to="2025-04-05T23:59:59Z"
     *   - Relative: reference="2025-04-29T14:30:00Z", offset="-30m"
     *
     *   Note: Narrower timeframes provide faster responses and more specific results.
     */
    timeframe:
      | {
          to: string;
          from: string;
        }
      | {
          reference: string;
          offset: string;
        };
    /**
     * Leave this empty to use the default datasets
     */
    datasets?: string[];
    filters?: {
      /**
       * Filter field name. IMPORTANT:
       *
       *     • DO NOT guess keys - always use verified keys from either:
       *       - Previous query results
       *       - The observability_keys response
       *
       *     • PREFERRED KEYS (faster & always available):
       *       - $metadata.service: Worker service name
       * 			- $metadata.origin: Trigger type (e.g., fetch, scheduled, etc.)
       * 			- $metadata.trigger: Trigger type (e.g., GET /users, POST /orders, etc.)
       *       - $metadata.message: Log message text (present in nearly all logs)
       *       - $metadata.error: Error message (when applicable)
       *
       */
      key: string;
      operation:
        | "includes"
        | "not_includes"
        | "starts_with"
        | "regex"
        | "exists"
        | "is_null"
        | "in"
        | "not_in"
        | "eq"
        | "neq"
        | "gt"
        | "gte"
        | "lt"
        | "lte";
      /**
       * Filter comparison value. IMPORTANT:
       *
       *     • MUST match actual values in your logs
       *     • VERIFY using either:
       *       - Actual values from previous query results
       *       - The '/values' endpoint with your selected key
       *
       *     • TYPE MATCHING:
       *       - Ensure value type (string/number/boolean) matches the field type
       *       - String comparisons are case-sensitive unless using specific operations
       *
       *     • PATTERN USAGE:
       *       - For 'contains', use simple wildcard patterns
       *       - For 'regex', MUST use ClickHouse regex syntax:
       *         - Uses RE2 syntax (not PCRE/JavaScript)
       *         - No lookaheads/lookbehinds
       *         - Examples: '^5\d{2}$' for HTTP 5xx codes, '\bERROR\b' for word boundary
       *         - Escape backslashes with double backslash
       */
      value?: string | number | boolean;
      type: "string" | "number" | "boolean";
    }[];
    /**
     *
     *     • ADVANCED USAGE:
     *       set limit=1000+ to retrieve comprehensive key options without needing additional filtering
     */
    limit?: number;
    needle?: {
      /**
       * Filter comparison value. IMPORTANT:
       *
       *     • MUST match actual values in your logs
       *     • VERIFY using either:
       *       - Actual values from previous query results
       *       - The '/values' endpoint with your selected key
       *
       *     • TYPE MATCHING:
       *       - Ensure value type (string/number/boolean) matches the field type
       *       - String comparisons are case-sensitive unless using specific operations
       *
       *     • PATTERN USAGE:
       *       - For 'contains', use simple wildcard patterns
       *       - For 'regex', MUST use ClickHouse regex syntax:
       *         - Uses RE2 syntax (not PCRE/JavaScript)
       *         - No lookaheads/lookbehinds
       *         - Examples: '^5\d{2}$' for HTTP 5xx codes, '\bERROR\b' for word boundary
       *         - Escape backslashes with double backslash
       */
      value: string | number | boolean;
      isRegex?: boolean;
      matchCase?: boolean;
    };
    keyNeedle?: Needle;
  };
}

export type ObservabilitykeysOutput = unknown;


/**
 * Find keys in the Workers Observability Data

## Best Practices
- Set a high limit (1000+) to ensure you see all available keys
- Add the $metadata.service filter to narrow results to a specific Worker

## Troubleshooting
- If expected fields are missing, verify the Worker is actively logging
- For empty results, try broadening your time range

 *
 * MCP server: `cloudflare-observability`
 * MCP tool: `observability_keys`
 * @param input Tool input
 * @returns Tool output
 */
export async function observabilityKeys(input: ObservabilitykeysInput): Promise<ObservabilitykeysOutput> {
  return await callMcpTool<ObservabilitykeysOutput>({
    serverName: "cloudflare-observability",
    toolName: "observability_keys",
    input,
  });
}

// CLI execution block
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  (async () => {
    try {
      let inputStr = "";
      if (process.stdin.isTTY) {
        // No stdin available, use empty object
        inputStr = "{}";
      } else {
        // Read from stdin (file descriptor 0)
        try {
          inputStr = readFileSync(0, "utf-8").trim();
        } catch {
          // Fallback if readFileSync fails
          inputStr = "";
        }
        if (!inputStr) {
          inputStr = "{}";
        }
      }
      
      const input = JSON.parse(inputStr) as ObservabilitykeysInput;
      const result = await observabilityKeys(input);
      console.log(JSON.stringify(result, null, 2));
      process.exit(0);
    } catch (error) {
      console.error("Error:", error instanceof Error ? error.message : String(error));
      if (error instanceof Error && error.stack) {
        console.error(error.stack);
      }
      process.exit(1);
    }
  })();
}
