#!/usr/bin/env tsx
import { callMcpTool } from "@merl-ai/mcp-toolbox-runtime";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";

// Generated by mcp-toolbox. Do not edit by hand.

export interface SetactiveaccountInput {
  /**
   * The accountId present in the users Cloudflare account, that should be the active accountId.
   */
  activeAccountIdParam: string;
}

export type SetactiveaccountOutput = unknown;


/**
 * Set active account to be used for tool calls that require accountId
 *
 * MCP server: `cloudflare-observability`
 * MCP tool: `set_active_account`
 * @param input Tool input
 * @returns Tool output
 */
export async function setActiveAccount(input: SetactiveaccountInput): Promise<SetactiveaccountOutput> {
  return await callMcpTool<SetactiveaccountOutput>({
    serverName: "cloudflare-observability",
    toolName: "set_active_account",
    input,
  });
}

// CLI execution block
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  (async () => {
    try {
      let inputStr = "";
      if (process.stdin.isTTY) {
        // No stdin available, use empty object
        inputStr = "{}";
      } else {
        // Read from stdin (file descriptor 0)
        try {
          inputStr = readFileSync(0, "utf-8").trim();
        } catch {
          // Fallback if readFileSync fails
          inputStr = "";
        }
        if (!inputStr) {
          inputStr = "{}";
        }
      }
      
      const input = JSON.parse(inputStr) as SetactiveaccountInput;
      const result = await setActiveAccount(input);
      console.log(JSON.stringify(result, null, 2));
      process.exit(0);
    } catch (error) {
      console.error("Error:", error instanceof Error ? error.message : String(error));
      if (error instanceof Error && error.stack) {
        console.error(error.stack);
      }
      process.exit(1);
    }
  })();
}
