#!/usr/bin/env tsx
import { callMcpTool } from "@merl-ai/mcp-toolbox-runtime";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";

// Generated by mcp-toolbox. Do not edit by hand.

export interface WorkerslistInput {}

export type WorkerslistOutput = unknown;

/**
 * List all Workers in your Cloudflare account.

If you only need details of a single Worker, use workers_get_worker.
 *
 * MCP server: `cloudflare-observability`
 * MCP tool: `workers_list`
 * @param input Tool input
 * @returns Tool output
 */
export async function workersList(
  input: WorkerslistInput
): Promise<WorkerslistOutput> {
  return await callMcpTool<WorkerslistOutput>({
    serverName: "cloudflare-observability",
    toolName: "workers_list",
    input,
  });
}

// CLI execution block
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  (async () => {
    try {
      let inputStr = "";
      if (process.stdin.isTTY) {
        // No stdin available, use empty object
        inputStr = "{}";
      } else {
        // Read from stdin (file descriptor 0)
        try {
          inputStr = readFileSync(0, "utf-8").trim();
        } catch {
          // Fallback if readFileSync fails
          inputStr = "";
        }
        if (!inputStr) {
          inputStr = "{}";
        }
      }

      const input = JSON.parse(inputStr) as WorkerslistInput;
      const result = await workersList(input);
      console.log(JSON.stringify(result, null, 2));
      process.exit(0);
    } catch (error) {
      console.error(
        "Error:",
        error instanceof Error ? error.message : String(error)
      );
      if (error instanceof Error && error.stack) {
        console.error(error.stack);
      }
      process.exit(1);
    }
  })();
}
