#!/usr/bin/env tsx
import { callMcpTool } from "@merl-ai/mcp-toolbox-runtime";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";

// Generated by mcp-toolbox. Do not edit by hand.

export interface WorkersgetworkerInput {
  /**
   * The name of the worker script to retrieve
   */
  scriptName: string;
}

export type WorkersgetworkerOutput = unknown;

/**
 * Get the details of the Cloudflare Worker.
 *
 * MCP server: `cloudflare-observability`
 * MCP tool: `workers_get_worker`
 * @param input Tool input
 * @returns Tool output
 */
export async function workersGetWorker(
  input: WorkersgetworkerInput,
): Promise<WorkersgetworkerOutput> {
  return await callMcpTool<WorkersgetworkerOutput>({
    serverName: "cloudflare-observability",
    toolName: "workers_get_worker",
    input,
  });
}

// CLI execution block
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  (async () => {
    try {
      let inputStr = "";
      if (process.stdin.isTTY) {
        // No stdin available, use empty object
        inputStr = "{}";
      } else {
        // Read from stdin (file descriptor 0)
        try {
          inputStr = readFileSync(0, "utf-8").trim();
        } catch {
          // Fallback if readFileSync fails
          inputStr = "";
        }
        if (!inputStr) {
          inputStr = "{}";
        }
      }

      const input = JSON.parse(inputStr) as WorkersgetworkerInput;
      const result = await workersGetWorker(input);
      console.log(JSON.stringify(result, null, 2));
      process.exit(0);
    } catch (error) {
      console.error("Error:", error instanceof Error ? error.message : String(error));
      if (error instanceof Error && error.stack) {
        console.error(error.stack);
      }
      process.exit(1);
    }
  })();
}
