#!/usr/bin/env tsx
import { callMcpTool } from "@merl-ai/mcp-toolbox-runtime";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";

// Generated by mcp-toolbox. Do not edit by hand.

export interface ApplymigrationInput {
  name: string;
  query: string;
}

export type ApplymigrationOutput = unknown;

/**
 * Applies a migration to the database. Use this when executing DDL operations. Do not hardcode references to generated IDs in data migrations.
 *
 * MCP server: `supabase`
 * MCP tool: `apply_migration`
 * @param input Tool input
 * @returns Tool output
 */
export async function applyMigration(input: ApplymigrationInput): Promise<ApplymigrationOutput> {
  return await callMcpTool<ApplymigrationOutput>({
    serverName: "supabase",
    toolName: "apply_migration",
    input,
  });
}

// CLI execution block
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  (async () => {
    try {
      let inputStr = "";
      if (process.stdin.isTTY) {
        // No stdin available, use empty object
        inputStr = "{}";
      } else {
        // Read from stdin (file descriptor 0)
        try {
          inputStr = readFileSync(0, "utf-8").trim();
        } catch {
          // Fallback if readFileSync fails
          inputStr = "";
        }
        if (!inputStr) {
          inputStr = "{}";
        }
      }

      const input = JSON.parse(inputStr) as ApplymigrationInput;
      const result = await applyMigration(input);
      console.log(JSON.stringify(result, null, 2));
      process.exit(0);
    } catch (error) {
      console.error("Error:", error instanceof Error ? error.message : String(error));
      if (error instanceof Error && error.stack) {
        console.error(error.stack);
      }
      process.exit(1);
    }
  })();
}
