#!/usr/bin/env tsx
import { callMcpTool } from "@merl-ai/mcp-toolbox-runtime";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";

// Generated by mcp-toolbox. Do not edit by hand.

export interface CreatebranchInput {
  /**
   * Name of the branch to create
   */
  name: string;
  /**
   * The cost confirmation ID. Call `confirm_cost` first.
   */
  confirm_cost_id: string;
}

export type CreatebranchOutput = unknown;


/**
 * Creates a development branch on a Supabase project. This will apply all migrations from the main project to a fresh branch database. Note that production data will not carry over. The branch will get its own project_id via the resulting project_ref. Use this ID to execute queries and migrations on the branch.
 *
 * MCP server: `supabase`
 * MCP tool: `create_branch`
 * @param input Tool input
 * @returns Tool output
 */
export async function createBranch(input: CreatebranchInput): Promise<CreatebranchOutput> {
  return await callMcpTool<CreatebranchOutput>({
    serverName: "supabase",
    toolName: "create_branch",
    input,
  });
}

// CLI execution block
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  (async () => {
    try {
      let inputStr = "";
      if (process.stdin.isTTY) {
        // No stdin available, use empty object
        inputStr = "{}";
      } else {
        // Read from stdin (file descriptor 0)
        try {
          inputStr = readFileSync(0, "utf-8").trim();
        } catch {
          // Fallback if readFileSync fails
          inputStr = "";
        }
        if (!inputStr) {
          inputStr = "{}";
        }
      }
      
      const input = JSON.parse(inputStr) as CreatebranchInput;
      const result = await createBranch(input);
      console.log(JSON.stringify(result, null, 2));
      process.exit(0);
    } catch (error) {
      console.error("Error:", error instanceof Error ? error.message : String(error));
      if (error instanceof Error && error.stack) {
        console.error(error.stack);
      }
      process.exit(1);
    }
  })();
}
