#!/usr/bin/env tsx
import { callMcpTool } from "mcp-toolbox-runtime";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";

// Generated by mcp-toolbox. Do not edit by hand.

export interface GeneratetypescripttypesInput {}

export type GeneratetypescripttypesOutput = unknown;

/**
 * Generates TypeScript types for a project.
 *
 * MCP server: `supabase`
 * MCP tool: `generate_typescript_types`
 * @param input Tool input
 * @returns Tool output
 */
export async function generateTypescriptTypes(
  input: GeneratetypescripttypesInput,
): Promise<GeneratetypescripttypesOutput> {
  return await callMcpTool<GeneratetypescripttypesOutput>({
    serverName: "supabase",
    toolName: "generate_typescript_types",
    input,
  });
}

// CLI execution block
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  (async () => {
    try {
      let inputStr = "";
      if (process.stdin.isTTY) {
        // No stdin available, use empty object
        inputStr = "{}";
      } else {
        // Read from stdin (file descriptor 0)
        try {
          inputStr = readFileSync(0, "utf-8").trim();
        } catch {
          // Fallback if readFileSync fails
          inputStr = "";
        }
        if (!inputStr) {
          inputStr = "{}";
        }
      }

      const input = JSON.parse(inputStr) as GeneratetypescripttypesInput;
      const result = await generateTypescriptTypes(input);
      console.log(JSON.stringify(result, null, 2));
      process.exit(0);
    } catch (error) {
      console.error("Error:", error instanceof Error ? error.message : String(error));
      if (error instanceof Error && error.stack) {
        console.error(error.stack);
      }
      process.exit(1);
    }
  })();
}
