#!/usr/bin/env tsx
import { callMcpTool } from "@merl-ai/mcp-toolbox-runtime";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";

// Generated by mcp-toolbox. Do not edit by hand.

export interface GetadvisorsInput {
  type: string;
}

export type GetadvisorsOutput = unknown;

/**
 * Gets a list of advisory notices for the Supabase project. Use this to check for security vulnerabilities or performance improvements. Include the remediation URL as a clickable link so that the user can reference the issue themselves. It's recommended to run this tool regularly, especially after making DDL changes to the database since it will catch things like missing RLS policies.
 *
 * MCP server: `supabase`
 * MCP tool: `get_advisors`
 * @param input Tool input
 * @returns Tool output
 */
export async function getAdvisors(input: GetadvisorsInput): Promise<GetadvisorsOutput> {
  return await callMcpTool<GetadvisorsOutput>({
    serverName: "supabase",
    toolName: "get_advisors",
    input,
  });
}

// CLI execution block
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  (async () => {
    try {
      let inputStr = "";
      if (process.stdin.isTTY) {
        // No stdin available, use empty object
        inputStr = "{}";
      } else {
        // Read from stdin (file descriptor 0)
        try {
          inputStr = readFileSync(0, "utf-8").trim();
        } catch {
          // Fallback if readFileSync fails
          inputStr = "";
        }
        if (!inputStr) {
          inputStr = "{}";
        }
      }

      const input = JSON.parse(inputStr) as GetadvisorsInput;
      const result = await getAdvisors(input);
      console.log(JSON.stringify(result, null, 2));
      process.exit(0);
    } catch (error) {
      console.error("Error:", error instanceof Error ? error.message : String(error));
      if (error instanceof Error && error.stack) {
        console.error(error.stack);
      }
      process.exit(1);
    }
  })();
}
