#!/usr/bin/env tsx
import { callMcpTool } from "@merl-ai/mcp-toolbox-runtime";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";

// Generated by mcp-toolbox. Do not edit by hand.

export interface ListtablesInput {
  /**
   * List of schemas to include. Defaults to all schemas.
   */
  schemas: string[];
}

export type ListtablesOutput = unknown;


/**
 * Lists all tables in one or more schemas.
 *
 * MCP server: `supabase`
 * MCP tool: `list_tables`
 * @param input Tool input
 * @returns Tool output
 */
export async function listTables(input: ListtablesInput): Promise<ListtablesOutput> {
  return await callMcpTool<ListtablesOutput>({
    serverName: "supabase",
    toolName: "list_tables",
    input,
  });
}

// CLI execution block
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  (async () => {
    try {
      let inputStr = "";
      if (process.stdin.isTTY) {
        // No stdin available, use empty object
        inputStr = "{}";
      } else {
        // Read from stdin (file descriptor 0)
        try {
          inputStr = readFileSync(0, "utf-8").trim();
        } catch {
          // Fallback if readFileSync fails
          inputStr = "";
        }
        if (!inputStr) {
          inputStr = "{}";
        }
      }
      
      const input = JSON.parse(inputStr) as ListtablesInput;
      const result = await listTables(input);
      console.log(JSON.stringify(result, null, 2));
      process.exit(0);
    } catch (error) {
      console.error("Error:", error instanceof Error ? error.message : String(error));
      if (error instanceof Error && error.stack) {
        console.error(error.stack);
      }
      process.exit(1);
    }
  })();
}
