#!/usr/bin/env tsx
import { callMcpTool } from "mcp-toolbox-runtime";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";

// Generated by mcp-toolbox. Do not edit by hand.

export interface RebasebranchInput {
  branch_id: string;
}

export type RebasebranchOutput = unknown;

/**
 * Rebases a development branch on production. This will effectively run any newer migrations from production onto this branch to help handle migration drift.
 *
 * MCP server: `supabase`
 * MCP tool: `rebase_branch`
 * @param input Tool input
 * @returns Tool output
 */
export async function rebaseBranch(input: RebasebranchInput): Promise<RebasebranchOutput> {
  return await callMcpTool<RebasebranchOutput>({
    serverName: "supabase",
    toolName: "rebase_branch",
    input,
  });
}

// CLI execution block
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  (async () => {
    try {
      let inputStr = "";
      if (process.stdin.isTTY) {
        // No stdin available, use empty object
        inputStr = "{}";
      } else {
        // Read from stdin (file descriptor 0)
        try {
          inputStr = readFileSync(0, "utf-8").trim();
        } catch {
          // Fallback if readFileSync fails
          inputStr = "";
        }
        if (!inputStr) {
          inputStr = "{}";
        }
      }

      const input = JSON.parse(inputStr) as RebasebranchInput;
      const result = await rebaseBranch(input);
      console.log(JSON.stringify(result, null, 2));
      process.exit(0);
    } catch (error) {
      console.error("Error:", error instanceof Error ? error.message : String(error));
      if (error instanceof Error && error.stack) {
        console.error(error.stack);
      }
      process.exit(1);
    }
  })();
}
